# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67f0a84a6ffcf9f27875784b2497d972b003dc8b627cdae3701d1ca1dd631675f026e717c484a60dcee6385a6f91f3675a016664d54c77959614d1e663d914a8

test:
  secret_key_base: 081195048fb23e9ffdd1a6a2edd3f3ca6395297f9767eb5ef8da7a9d7e2c311f3ca9531e0f68ffa3c08404f64b313c1cbab8d9f9c47ec0ec644f1293641940d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
